site_name: Anfora Docs
theme:
        name: 'material'

nav:
    - About: index.md
    - Installation: getting-started.md
    - Development: development.md
    - API:
        - Entities: entities.md
        - Rest API: 
            - Media: rest/media.md
        - Client API: client.md